apiVersion: v1
data:
 mapRoles: |
  - groups:
    - system:masters
    rolearn: arn:aws:iam::341685272394:role/UdacityFlaskDeployCBKubectlRole
    username: build
  - groups:
    - system:bootstrappers
    - system:nodes
    rolearn: arn:aws:iam::341685272394:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1536HHCXULVNM
    username: system:node:{{EC2PrivateDNSName}}
 mapUsers: |
  []
kind: ConfigMap
metadata:
 creationTimestamp: '2021-03-19T17:14:42Z'
 managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
     f:data:
      .: {}
      f:mapRoles: {}
      f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: '2021-03-19T17:14:42Z'
 name: aws-auth
 namespace: kube-system
 resourceVersion: '1581'
 selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
 uid: 3f55a380-d93b-40e3-b7d8-5ae727639f71
